In [3]:
import numpy as np

In [4]:
my_list = [1,2,3,4,5]

arr = np.array(my_list)

In [19]:
print(arr)

[0 2 4 6 8]


In [12]:
arr.shape

(3, 5)

In [7]:
type(arr)

numpy.ndarray

In [13]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [11,12,13,14,15]

arr = np.array([list1,list2,list3])

In [14]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [22]:
arr = np.arange(0,10)

In [ ]:
arr = np.arange(0,10,2)

In [23]:
arr == 2

array([False, False,  True, False, False, False, False, False, False,
       False])

In [24]:
arr > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [30]:
arr[arr>2]


array([3, 4, 5, 6, 7, 8, 9])